name: GitHub Profile Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Generate Snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Satyansh-Yadav0812
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Generate 3D Calendar
      - name: Generate 3D Calendar
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Satyansh-Yadav0812

      # Merge outputs
      - name: Copy 3D Calendar
        run: |
          cp -r profile-3d-contrib/* dist/

      # Deploy everything
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
